const APP_VERSION="0.2.1";
const GAS_URL="https://script.google.com/macros/s/AKfycbzUJb7b8I7w5HG7h7OeR-43vawtbcBiudTLO2qzOhOrt4O9IYxIRnhObWn9-n3Io5dUoA/exec";
const SIZE=15,WALL=0,FLOOR=1;
const DIRS={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0],"up-left":[-1,-1],"up-right":[1,-1],"down-left":[-1,1],"down-right":[1,1]};
const DUN={beginner:{id:"beginner",name:"初心者の洞窟",max:10,dif:1,startG:80},herb:{id:"herb",name:"薬草の迷宮",max:15,dif:1.25,startG:60},deep:{id:"deep",name:"もっと不思議な迷宮",max:30,dif:1.6,startG:30}};
const ITEMS={
 h1:{cat:"herb",ic:"草",n:"薬草",u:"未識別の草",p:40,d:"HPを25回復"},h2:{cat:"herb",ic:"草",n:"大きな薬草",u:"未識別の草",p:90,d:"HPを60回復"},hp:{cat:"herb",ic:"草",n:"ちからの草",u:"未識別の草",p:120,d:"攻撃+1"},po:{cat:"herb",ic:"草",n:"どくけし草",u:"未識別の草",p:55,d:"毒を治す"},bread:{cat:"food",ic:"食",n:"パン",u:"パン",p:50,d:"満腹度+50"},
 sw1:{cat:"weapon",ic:"剣",n:"木の剣",u:"木の剣",pow:2,p:120,d:"攻撃+2"},sw2:{cat:"weapon",ic:"剣",n:"鉄の剣",u:"鉄の剣",pow:4,p:260,d:"攻撃+4"},sws:{cat:"weapon",ic:"剣",n:"ねむりの剣",u:"ねむりの剣",pow:3,p:420,d:"攻撃+3、たまに眠り"},
 sh1:{cat:"shield",ic:"盾",n:"木の盾",u:"木の盾",pow:2,p:120,d:"防御+2"},sh2:{cat:"shield",ic:"盾",n:"鉄の盾",u:"鉄の盾",pow:4,p:260,d:"防御+4"},
 rp:{cat:"ring",ic:"指",n:"ちからの指輪",u:"未識別の指輪",p:350,d:"攻撃+2"},rf:{cat:"ring",ic:"指",n:"腹もちの指輪",u:"未識別の指輪",p:330,d:"満腹度の減り半減"},rg:{cat:"ring",ic:"指",n:"毒よけの指輪",u:"未識別の指輪",p:300,d:"毒を防ぐ"},
 si:{cat:"scroll",ic:"巻",n:"識別の巻物",u:"未識別の巻物",p:120,d:"持ち物をすべて識別"},st:{cat:"scroll",ic:"巻",n:"いかずちの巻物",u:"未識別の巻物",p:180,d:"周囲の敵に25ダメージ"},ww:{cat:"scroll",ic:"巻",n:"ワープの巻物",u:"未識別の巻物",p:100,d:"ワープ"},sr:{cat:"scroll",ic:"巻",n:"帰還の巻物",u:"未識別の巻物",p:280,d:"持ち物を持って帰還"},
 wf:{cat:"wand",ic:"杖",n:"火ばしらの杖",u:"未識別の杖",p:260,d:"近い敵に20ダメージ",ch:[3,6]},ws:{cat:"wand",ic:"杖",n:"鈍足の杖",u:"未識別の杖",p:220,d:"近い敵を鈍足",ch:[3,6]},wb:{cat:"wand",ic:"杖",n:"ふきとばしの杖",u:"未識別の杖",p:180,d:"近い敵を吹き飛ばす",ch:[3,6]},wx:{cat:"wand",ic:"杖",n:"場所替えの杖",u:"未識別の杖",p:240,d:"敵と場所替え",ch:[2,5]},
 ph:{cat:"pot",ic:"壺",n:"回復の壺",u:"未識別の壺",p:260,d:"HPを40回復",ch:[2,4]},pi:{cat:"pot",ic:"壺",n:"識別の壺",u:"未識別の壺",p:340,d:"持ち物をすべて識別",ch:[1,3]},ps:{cat:"pot",ic:"壺",n:"保存の壺",u:"未識別の壺",p:380,d:"持ち物上限+4",ch:[1,1]}
};
const DROP={beginner:["h1","bread","sw1","sh1","si","st","wf","ph","rp"],herb:["h1","h2","hp","po","bread","sw2","sh2","si","st","ww","wf","ws","wb","ph","pi","ps","rf","rg"],deep:Object.keys(ITEMS)};
const EN=[{id:"sl",n:"分裂スライム",ic:"ぷ",hp:10,a:3,ex:6,ab:"split"},{id:"bt",n:"はやてコウモリ",ic:"こ",hp:9,a:4,ex:8,ab:"fast"},{id:"mg",n:"火吹きまどうし",ic:"魔",hp:12,a:5,ex:13,ab:"range"},{id:"th",n:"ぬすっと小僧",ic:"盗",hp:11,a:4,ex:12,ab:"steal"},{id:"gh",n:"かべぬけゴースト",ic:"霊",hp:16,a:6,ex:16,ab:"ghost"},{id:"po",n:"どくサソリ",ic:"毒",hp:15,a:7,ex:18,ab:"poison"}];
const $=id=>document.getElementById(id),E={name:$("playerName"),ds:$("dungeonSelect"),b:$("board"),log:$("log"),inv:$("inventory"),wh:$("warehouse"),shop:$("shop"),bag:$("bagInfo"),rank:$("ranking"),rn:$("rankingNote"),res:$("result"),rt:$("resultTitle"),rx:$("resultText"),sub:$("btnSubmit"),sf:$("stFloor"),sl:$("stLevel"),hp:$("stHp"),fo:$("stFood"),go:$("stGold"),sc:$("stScore"),ew:$("eqWeapon"),es:$("eqShield"),er:$("eqRing")};
let S=null,last=null,sel="",selWh="";
const R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,C=a=>a[R(0,a.length-1)],id=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function item(k,known=false){const d=ITEMS[k];let it={id:id(),k,cat:d.cat,ic:d.ic,n:d.n,u:d.u,p:d.p,d:d.d,pow:d.pow||0,known};if(d.ch)it.ch=R(d.ch[0],d.ch[1]);return it}
function dn(it){if(!it)return"なし";return(it.known||S?.known[it.k]?it.n:it.u)+(it.ch!=null&&(it.known||S?.known[it.k])?`［${it.ch}］`:"")}
function dd(it){return(it.known||S?.known[it.k])?it.d:"正体不明。使う・装備・識別で判明"}
function know(k){S.known[k]=true;S.p.inv.forEach(x=>{if(x.k===k)x.known=true});Object.values(S.p.eq).forEach(x=>{if(x&&x.k===k)x.known=true})}
function init(){E.name.value=localStorage.md_player_name||"";E.ds.value=localStorage.md_dungeon_id||"beginner";bind();empty();renderWh();loadRank();sw()}
function bind(){
 $("btnNewGame").onclick=start;$("btnRanking").onclick=loadRank;$("btnUpdate").onclick=hardUpdate;$("btnWait").onclick=()=>turn(0,0);$("btnUse").onclick=use;$("btnEquip").onclick=equip;$("btnReturn").onclick=ret;$("btnGiveUp").onclick=giveup;$("btnTakeWh").onclick=takeWh;E.sub.onclick=submit;$("btnClose").onclick=()=>E.res.close();E.ds.onchange=()=>{localStorage.md_dungeon_id=E.ds.value;loadRank()};
 document.querySelectorAll("[data-dir]").forEach(x=>x.onclick=()=>{let [dx,dy]=DIRS[x.dataset.dir];turn(dx,dy)});
 window.addEventListener("keydown",ev=>{if(!S||S.end||E.res.open)return;let m={ArrowUp:"up",ArrowDown:"down",ArrowLeft:"left",ArrowRight:"right",w:"up",s:"down",a:"left",d:"right",q:"up-left",e:"up-right",z:"down-left",c:"down-right",".":"wait"," ":"wait"};let d=m[ev.key]||m[String(ev.key).toLowerCase()];if(!d)return;ev.preventDefault();if(d==="wait")turn(0,0);else{let [dx,dy]=DIRS[d];turn(dx,dy)}})
}
function start(){let name=(E.name.value||"名無し").replace(/[<>]/g,"").trim()||"名無し",du=DUN[E.ds.value]||DUN.beginner;localStorage.md_player_name=name;localStorage.md_dungeon_id=du.id;let carry=JSON.parse(localStorage.md_pending_items||"[]").slice(0,8);localStorage.removeItem("md_pending_items");S={name,du,f:1,t:0,map:[],items:[],en:[],shop:null,st:{x:13,y:13},def:0,end:false,log:[],known:{bread:true,sw1:true,sw2:true,sws:true,sh1:true,sh2:true},p:{x:1,y:1,hp:36,mhp:36,lv:1,ex:0,atk:6,def:1,food:100,g:du.startG,poison:false,bagPlus:0,eq:{weapon:null,shield:null,ring:null},inv:[item("h1",true),item("bread",true),...carry]}};sel="";floor(true);log(`${du.name}に挑戦します。`);log("未識別アイテム、装備、壺、杖、店、倉庫を追加済みです。");render();renderWh();loadRank()}
function floor(first=false){S.map=genMap();S.en=[];S.items=[];S.shop=null;let fs=floors();let p=first?{x:1,y:1}:C(fs);S.p.x=p.x;S.p.y=p.y;S.st=far(p,fs);for(let i=0;i<cl(3+Math.floor(S.f/2),3,11);i++)spawn();for(let i=0;i<cl(4+Math.floor(S.f/4),4,8);i++){let q=emptyTile();S.items.push({...randItem(),x:q.x,y:q.y})}if(S.f>=2&&(S.f%3===0||Math.random()<.18))mkShop();if(!first){S.p.hp=cl(S.p.hp+8,1,S.p.mhp);S.p.food=cl(S.p.food+5,0,100)}}
function genMap(){let m=Array.from({length:SIZE},()=>Array.from({length:SIZE},(_,x)=>x===0||x===SIZE-1?WALL:FLOOR));for(let y=0;y<SIZE;y++){m[y][0]=m[y][SIZE-1]=WALL}for(let i=0;i<34;i++){let x=R(1,13),y=R(1,13);if(!(x<=2&&y<=2)&&Math.random()<.35)m[y][x]=WALL}m[1][1]=FLOOR;return m}
function floors(){let a=[];for(let y=1;y<14;y++)for(let x=1;x<14;x++)if(S.map[y][x]===FLOOR)a.push({x,y});return a}
function far(p,a){return[...a].sort((u,v)=>Math.abs(v.x-p.x)+Math.abs(v.y-p.y)-Math.abs(u.x-p.x)-Math.abs(u.y-p.y))[0]||{x:13,y:13}}
function emptyTile(){let a=floors();for(let i=0;i<300;i++){let p=C(a);if(p.x===S.p.x&&p.y===S.p.y)continue;if(p.x===S.st.x&&p.y===S.st.y)continue;if(S.en.some(e=>e.x===p.x&&e.y===p.y))continue;if(S.items.some(e=>e.x===p.x&&e.y===p.y))continue;if(S.shop&&S.shop.x===p.x&&S.shop.y===p.y)continue;return p}return C(a)}
function randItem(){let k=C(DROP[S.du.id]||DROP.beginner);if(S.f>=8&&Math.random()<.25)k=C(["sw2","sh2","rf","rg","ps","ws","sr"]);return item(k,false)}
function spawn(){let p=emptyTile(),base=S.f<=2?EN[0]:S.f<=4?C(EN.slice(0,2)):S.f<=7?C(EN.slice(0,4)):S.f<=12?C(EN.slice(1,5)):C(EN),d=S.du.dif;S.en.push({id:id(),x:p.x,y:p.y,n:base.n,ic:base.ic,ab:base.ab,hp:Math.floor((base.hp+S.f*2)*d),mhp:Math.floor((base.hp+S.f*2)*d),atk:Math.floor((base.a+Math.floor(S.f/2))*d),ex:Math.floor((base.ex+S.f)*d),slow:0,sleep:0,stole:false})}
function mkShop(){let p=emptyTile(),goods=[];for(let i=0;i<R(3,5);i++){let it=randItem();it.p=Math.floor(it.p*1.2);goods.push(it)}S.shop={x:p.x,y:p.y,goods}}
function turn(dx,dy){if(!S||S.end)return;let acted=false;if(dx===0&&dy===0){log("その場で様子を見ました。");acted=true}else{let nx=S.p.x+dx,ny=S.p.y+dy;if(!inside(nx,ny)||S.map[ny][nx]===WALL)log("壁にぶつかりました。");else{let e=S.en.find(e=>e.x===nx&&e.y===ny);if(e){attack(e);acted=true}else{S.p.x=nx;S.p.y=ny;acted=true;pickup();stairs()}}}if(!acted||S.end){render();return}after()}
function after(){S.t++;hunger();if(S.end){render();return}enemyTurn();if(S.end){render();return}if(S.t%8===0&&S.p.hp<S.p.mhp&&S.p.food>0)S.p.hp++;render()}
function atk(){let v=S.p.atk+(S.p.eq.weapon?.pow||0)+(S.p.eq.ring?.k==="rp"?2:0);return S.p.poison?Math.max(1,v-2):v}function def(){return S.p.def+(S.p.eq.shield?.pow||0)}
function attack(e){let dm=Math.max(1,atk()+R(-2,3));e.hp-=dm;log(`${e.n}に${dm}ダメージ。`);if(S.p.eq.weapon?.k==="sws"&&Math.random()<.18){e.sleep=3;log(`${e.n}は眠った。`)}if(e.ab==="split"&&e.hp>0&&Math.random()<.12){let p=adj(e.x,e.y);if(p){S.en.push({...e,id:id(),x:p.x,y:p.y,hp:Math.max(4,Math.floor(e.hp/2))});log(`${e.n}が分裂しました。`)}}if(e.hp<=0)kill(e)}
function kill(e){S.en=S.en.filter(x=>x.id!==e.id);S.def++;S.p.ex+=e.ex;S.p.g+=R(4,14)+S.f;log(`${e.n}を倒しました。`);if(Math.random()<.18){S.items.push({...randItem(),x:e.x,y:e.y});log("アイテムを落としました。")}while(S.p.ex>=S.p.lv*20){S.p.ex-=S.p.lv*20;S.p.lv++;S.p.mhp+=6;S.p.hp=S.p.mhp;S.p.atk+=2;S.p.def++;log(`レベル${S.p.lv}に上がりました。`)}}
function hunger(){let use=S.p.eq.ring?.k==="rf"?(S.t%2===0?1:0):1;S.p.food=cl(S.p.food-use,0,100);if(S.p.food===20)log("お腹が空いてきました。");if(S.p.food===0){S.p.hp-=2;log("空腹で2ダメージ。");if(S.p.hp<=0)finish("空腹で倒れました。",false,false)}}
function enemyTurn(){for(const e of [...S.en]){if(S.end)return;if(e.sleep>0){e.sleep--;continue}let n=e.ab==="fast"&&Math.random()<.55?2:1;for(let i=0;i<n;i++){if(!S.en.includes(e)||S.end)break;if(e.slow>0){e.slow--;if(i===0)continue}enemyAct(e)}}}
function enemyAct(e){let d=Math.max(Math.abs(e.x-S.p.x),Math.abs(e.y-S.p.y));if(e.ab==="range"&&d>1&&d<=4&&Math.random()<.6){let dm=Math.max(3,e.atk+R(1,4)-Math.floor(def()/2));S.p.hp-=dm;log(`${e.n}の炎。${dm}ダメージ。`);if(S.p.hp<=0)finish(`${e.n}に倒されました。`,false,false);return}if(d<=1)enemyAtk(e);else if(d<=7){let dx=Math.sign(S.p.x-e.x),dy=Math.sign(S.p.y-e.y);moveE(e,dx,dy)||moveE(e,dx,0)||moveE(e,0,dy)}else if(Math.random()<.35){let [dx,dy]=C(Object.values(DIRS));moveE(e,dx,dy)}}
function enemyAtk(e){if(e.ab==="steal"&&!e.stole&&Math.random()<.45){e.stole=true;if(S.p.g>=20){let g=Math.min(S.p.g,R(20,70));S.p.g-=g;log(`${e.n}に${g}G盗まれました。`)}else if(S.p.inv.length){let it=S.p.inv.splice(R(0,S.p.inv.length-1),1)[0];log(`${e.n}に${dn(it)}を盗まれました。`)}moveE(e,Math.sign(e.x-S.p.x),Math.sign(e.y-S.p.y));return}let dm=Math.max(1,e.atk-def()+R(-1,3));S.p.hp-=dm;log(`${e.n}の攻撃。${dm}ダメージ。`);if(e.ab==="poison"&&Math.random()<.25){if(S.p.eq.ring?.k==="rg")log("毒よけの指輪が毒を防ぎました。");else{S.p.poison=true;log("毒を受けました。攻撃力低下。")}}if(S.p.hp<=0)finish(`${e.n}に倒されました。`,false,false)}
function moveE(e,dx,dy){let nx=e.x+dx,ny=e.y+dy;if(!inside(nx,ny))return false;if(e.ab!=="ghost"&&S.map[ny][nx]===WALL)return false;if(S.p.x===nx&&S.p.y===ny)return false;if(S.en.some(o=>o.id!==e.id&&o.x===nx&&o.y===ny))return false;e.x=nx;e.y=ny;return true}
function adj(x,y){for(const [dx,dy] of Object.values(DIRS)){let nx=x+dx,ny=y+dy;if(inside(nx,ny)&&S.map[ny][nx]===FLOOR&&!(S.p.x===nx&&S.p.y===ny)&&!S.en.some(e=>e.x===nx&&e.y===ny))return{x:nx,y:ny}}return null}
function pickup(){let i=S.items.findIndex(it=>it.x===S.p.x&&it.y===S.p.y);if(i<0)return;if(S.p.inv.length>=bagMax()){log("持ち物がいっぱいです。");return}let it=S.items.splice(i,1)[0];delete it.x;delete it.y;S.p.inv.push(it);sel=it.id;log(`${dn(it)}を拾いました。`)}
function stairs(){if(S.p.x!==S.st.x||S.p.y!==S.st.y)return;if(S.f>=S.du.max){finish("最深部に到達しました。ダンジョンクリア！",true,true);return}S.f++;log(`${S.f}階へ進みました。`);floor(false)}
function bagMax(){return 12+S.p.bagPlus}
function use(){if(!S||S.end)return;let it=S.p.inv.find(x=>x.id===sel);if(!it){log("使うアイテムを選択してください。");render();return}know(it.k);if(["weapon","shield","ring"].includes(it.cat)){log(`${it.n}は装備できます。`);render();return}let consume=true;if(it.k==="h1")heal(25);else if(it.k==="h2")heal(60);else if(it.k==="hp"){S.p.atk++;log("ちからが上がりました。")}else if(it.k==="po"){S.p.poison=false;log("毒が消えました。")}else if(it.k==="bread"){S.p.food=cl(S.p.food+50,0,100);log("パンを食べました。満腹度回復。")}else if(it.k==="si"){S.p.inv.forEach(x=>know(x.k));log("持ち物を識別しました。")}else if(it.k==="st")thunder();else if(it.k==="ww")warp();else if(it.k==="sr"){removeIt(it.id);finish("帰還の巻物で無事に帰りました。",false,true);return}else if(it.cat==="wand")wand(it);else if(it.cat==="pot")pot(it);if(consume){if(it.ch!=null){it.ch--;if(it.ch<=0){log(`${it.n}は空になりました。`);removeIt(it.id)}}else removeIt(it.id)}after()}
function equip(){if(!S||S.end)return;let it=S.p.inv.find(x=>x.id===sel);if(!it){log("装備するアイテムを選択してください。");render();return}if(!["weapon","shield","ring"].includes(it.cat)){log(`${dn(it)}は装備できません。`);render();return}know(it.k);let slot=it.cat==="weapon"?"weapon":it.cat==="shield"?"shield":"ring",old=S.p.eq[slot];S.p.eq[slot]=it;S.p.inv=S.p.inv.filter(x=>x.id!==it.id);if(old)S.p.inv.push(old);sel="";log(`${it.n}を装備しました。`);after()}
function heal(n){S.p.hp=cl(S.p.hp+n,1,S.p.mhp);log(`HPが${n}回復しました。`)}
function thunder(){let a=S.en.filter(e=>Math.max(Math.abs(e.x-S.p.x),Math.abs(e.y-S.p.y))<=4);if(!a.length){log("近くに敵がいません。");return}log("雷が周囲の敵を打ちました。");a.forEach(e=>e.hp-=25);[...a].forEach(e=>{if(e.hp<=0)kill(e)})}
function warp(){let p=emptyTile();S.p.x=p.x;S.p.y=p.y;log("ワープしました。")}
function nearEnemy(){let best=null,bd=99;S.en.forEach(e=>{let d=Math.max(Math.abs(e.x-S.p.x),Math.abs(e.y-S.p.y));if(d<bd&&d<=7){best=e;bd=d}});return best}
function wand(it){let e=nearEnemy();if(!e){log("近くに敵がいません。");return}if(it.k==="wf"){e.hp-=20;log(`${e.n}に20ダメージ。`);if(e.hp<=0)kill(e)}else if(it.k==="ws"){e.slow=4;log(`${e.n}を鈍足にしました。`)}else if(it.k==="wb"){let dx=Math.sign(e.x-S.p.x),dy=Math.sign(e.y-S.p.y);for(let i=0;i<4;i++)if(!moveE(e,dx,dy))break;log(`${e.n}を吹き飛ばしました。`)}else if(it.k==="wx"){let x=S.p.x,y=S.p.y;S.p.x=e.x;S.p.y=e.y;e.x=x;e.y=y;log(`${e.n}と場所替えしました。`)}}
function pot(it){if(it.k==="ph")heal(40);else if(it.k==="pi"){S.p.inv.forEach(x=>know(x.k));log("識別の壺で識別しました。")}else if(it.k==="ps"){S.p.bagPlus+=4;log("持ち物上限が4増えました。")}}
function removeIt(i){S.p.inv=S.p.inv.filter(x=>x.id!==i);if(sel===i)sel=""}
function buy(i){if(!S||!S.shop)return;let it=S.shop.goods[i];if(!it)return;if(S.p.g<it.p){log("ゴールドが足りません。");render();return}if(S.p.inv.length>=bagMax()){log("持ち物がいっぱいです。");render();return}S.p.g-=it.p;S.p.inv.push(it);S.shop.goods.splice(i,1);sel=it.id;log(`${dn(it)}を購入しました。`);render()}
function ret(){if(S&&!S.end)finish("無事に帰還しました。",false,true)}function giveup(){if(S&&!S.end)finish("冒険をあきらめました。持ち物と装備は失われました。",false,false)}
function finish(msg,clear,keep){if(!S||S.end)return;S.end=true;last={name:S.name,score:score(clear),floor:S.f,level:S.p.lv,gold:S.p.g,defeated:S.def,turn:S.t,cleared:clear,dungeonId:S.du.id,dungeonName:S.du.name,version:APP_VERSION,createdAt:new Date().toISOString()};saveLocal(last);if(keep)depositAll();render();renderWh();E.rt.textContent=clear?"ダンジョンクリア！":"冒険終了";E.rx.innerHTML=`${esc(msg)}<br>ダンジョン：${esc(S.du.name)}<br>スコア：<b>${last.score}</b><br>到達階：${S.f}階 / Lv：${S.p.lv} / 討伐：${S.def}体 / G：${S.p.g}`;E.sub.disabled=false;E.res.showModal();loadRank()}
function score(clear=false){return Math.floor(S.f*140*S.du.dif+S.p.lv*90+S.p.g+S.def*28+Math.max(0,S.p.hp)*3+S.p.inv.length*15+(clear?S.du.max*180:0))}
function empty(){E.b.innerHTML="";for(let i=0;i<SIZE*SIZE;i++){let d=document.createElement("div");d.className="cell wall";E.b.appendChild(d)}update();renderInv();renderShop()}
function render(){if(!S){empty();return}let im=new Map(S.items.map(x=>[`${x.x},${x.y}`,x])),em=new Map(S.en.map(x=>[`${x.x},${x.y}`,x]));E.b.innerHTML="";for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){let d=document.createElement("div"),k=`${x},${y}`;d.className="cell "+(S.map[y][x]===WALL?"wall":"floor");if(S.p.x===x&&S.p.y===y){d.className="cell player";d.textContent="主"}else if(em.has(k)){let e=em.get(k);d.className="cell enemy";d.textContent=e.ic;d.title=`${e.n} HP:${e.hp}/${e.mhp}`}else if(S.st.x===x&&S.st.y===y){d.className="cell stairs";d.textContent="▽"}else if(S.shop&&S.shop.x===x&&S.shop.y===y){d.className="cell shopTile";d.textContent="店"}else if(im.has(k)){let it=im.get(k);d.className="cell item";d.textContent=it.ic;d.title=dn(it)}else if(S.map[y][x]===FLOOR)d.textContent="·";E.b.appendChild(d)}update();renderInv();renderShop();renderLog()}
function update(){let d=S?.du||DUN[E.ds.value]||DUN.beginner;E.sf.textContent=S?`${S.f}/${d.max}`:"-";E.sl.textContent=S?S.p.lv:"-";E.hp.textContent=S?`${S.p.hp}/${S.p.mhp}`:"-";E.fo.textContent=S?S.p.food:"-";E.go.textContent=S?S.p.g:"-";E.sc.textContent=S?score(false):"-";E.ew.textContent=S?dn(S.p.eq.weapon):"なし";E.es.textContent=S?dn(S.p.eq.shield):"なし";E.er.textContent=S?dn(S.p.eq.ring):"なし"}
function renderInv(){if(!S){E.inv.textContent="冒険前です。倉庫から持ち出して開始できます。";E.bag.textContent="-";return}E.bag.textContent=`持ち物 ${S.p.inv.length}/${bagMax()} / 攻撃 ${atk()} / 防御 ${def()}${S.p.poison?" / 毒":""}`;E.inv.innerHTML="";if(!S.p.inv.length){E.inv.textContent="持ち物なし";return}S.p.inv.forEach(it=>{let b=document.createElement("button");b.className="row"+(sel===it.id?" sel":"");b.innerHTML=`${esc(it.ic)} ${esc(dn(it))}<span class="desc">${esc(dd(it))}</span>`;b.onclick=()=>{sel=it.id;renderInv()};E.inv.appendChild(b)})}
function renderShop(){E.shop.innerHTML="";if(!S||!S.shop||S.p.x!==S.shop.x||S.p.y!==S.shop.y){E.shop.className="list muted";E.shop.textContent="店に乗ると商品が表示されます。";return}E.shop.className="list";if(!S.shop.goods.length){E.shop.textContent="売り切れです。";return}S.shop.goods.forEach((it,i)=>{let r=document.createElement("div");r.className="shopItem";r.innerHTML=`<div>${esc(it.ic)} ${esc(dn(it))}<span class="desc">${it.p}G / ${esc(dd(it))}</span></div>`;let b=document.createElement("button");b.textContent="購入";b.onclick=()=>buy(i);r.appendChild(b);E.shop.appendChild(r)})}
function renderLog(){E.log.innerHTML="";(S?S.log.slice(-90):[]).slice().reverse().forEach(x=>{let d=document.createElement("div");d.textContent=x;E.log.appendChild(d)})}function log(x){if(S)S.log.push(x)}function inside(x,y){return x>=0&&y>=0&&x<SIZE&&y<SIZE}
function wh(){return JSON.parse(localStorage.md_warehouse_v021||"[]")}function writeWh(a){localStorage.md_warehouse_v021=JSON.stringify(a.slice(0,80))}function renderWh(){let a=wh();E.wh.innerHTML="";if(!a.length){E.wh.textContent="倉庫は空です。";return}a.forEach(it=>{let b=document.createElement("button");b.className="row"+(selWh===it.id?" sel":"");b.innerHTML=`${esc(it.ic)} ${esc(it.n+(it.ch!=null?`［${it.ch}］`:""))}<span class="desc">${esc(it.d||"")}</span>`;b.onclick=()=>{selWh=it.id;renderWh()};E.wh.appendChild(b)})}
function takeWh(){if(S&&!S.end){log("冒険中は倉庫から持ち出せません。");render();return}let a=wh(),i=a.findIndex(x=>x.id===selWh);if(i<0)return;let p=JSON.parse(localStorage.md_pending_items||"[]");if(p.length>=8){alert("持ち出しは最大8個です。");return}p.push(a.splice(i,1)[0]);writeWh(a);localStorage.md_pending_items=JSON.stringify(p);selWh="";renderWh();alert("次回冒険の持ち物に入れました。")}
function depositAll(){let a=wh();S.p.inv.forEach(it=>{it.known=true;a.push(it)});Object.values(S.p.eq).forEach(it=>{if(it){it.known=true;a.push(it)}});S.p.inv=[];S.p.eq={weapon:null,shield:null,ring:null};writeWh(a)}
function rkey(){return`md_rank_v021_${E.ds.value||"beginner"}`}function saveLocal(r){let a=JSON.parse(localStorage.getItem(`md_rank_v021_${r.dungeonId}`)||"[]");a.push(r);a.sort((x,y)=>y.score-x.score);localStorage.setItem(`md_rank_v021_${r.dungeonId}`,JSON.stringify(a.slice(0,20)))}function localRank(){return JSON.parse(localStorage.getItem(rkey())||"[]").sort((x,y)=>y.score-x.score).slice(0,10)}
async function submit(){if(!last)return;E.sub.disabled=true;try{let p=new URLSearchParams();Object.entries(last).forEach(([k,v])=>p.append(k,String(v)));await fetch(GAS_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:p.toString()});E.rn.textContent="共有ランキングへ送信しました。";setTimeout(loadRank,1500)}catch(e){E.rn.textContent="共有ランキング送信に失敗。ローカルランキングを表示します。";loadRank()}}
async function loadRank(){let did=E.ds.value||"beginner",du=DUN[did]||DUN.beginner,a=localRank();showRank(a,`${du.name}：共有ランキングを取得中...`);try{let r=await jsonp(`${GAS_URL}?action=ranking&dungeonId=${encodeURIComponent(did)}&limit=10`);showRank(Array.isArray(r.ranking)?r.ranking:a,`${du.name}：共有ランキングを表示中です。`)}catch(e){showRank(a,"共有ランキングを取得できませんでした。ローカルランキングを表示中です。")}}
function showRank(a,note){E.rank.innerHTML="";if(!a.length){let li=document.createElement("li");li.textContent="まだ記録がありません";E.rank.appendChild(li)}else a.slice(0,10).forEach(r=>{let li=document.createElement("li");li.textContent=`${r.cleared===true||r.cleared==="true"?"★":""}${r.name||"名無し"}：${r.score||0}点（${r.floor||"-"}F / Lv${r.level||"-"}）`;E.rank.appendChild(li)});E.rn.textContent=note}
function jsonp(url){return new Promise((ok,ng)=>{let cb="mdcb"+Date.now()+R(1,99999),s=document.createElement("script"),t=setTimeout(()=>{clean();ng(new Error("timeout"))},10000);function clean(){clearTimeout(t);delete window[cb];s.remove()}window[cb]=d=>{clean();ok(d)};s.onerror=()=>{clean();ng(new Error("jsonp"))};s.src=url+(url.includes("?")?"&":"?")+`callback=${cb}&_=${Date.now()}`;document.body.appendChild(s)})}
async function sw(){if(!("serviceWorker"in navigator))return;try{let r=await navigator.serviceWorker.register("./sw.js?v="+APP_VERSION);r.update()}catch(e){}}
async function hardUpdate(){try{if("serviceWorker"in navigator){let r=await navigator.serviceWorker.getRegistrations();await Promise.all(r.map(x=>x.unregister()))}if("caches"in window){let k=await caches.keys();await Promise.all(k.map(x=>caches.delete(x)))}}catch(e){}let u=new URL(location.href);u.searchParams.set("reload",Date.now());location.replace(u.toString())}
init();
